export { default as Banner } from "./Banner";
export { default as DiscountBanner } from "./DiscountBanner";
export { default as FlashDeals } from "./FlashDeals";
export { default as NewArrivals } from "./NewArrivals";
export { default as OurServices } from "./OurServices";
export { default as RandomProducts } from "./RandomProducts";
export { default as SideBarShoppingCart } from "./SideBarShoppingCart";
export { default as SideBarShoppingCartItem } from "./SideBarShoppingCartItem";
export { default as TopCategories } from "./TopCategories";
