import Head from "next/head";
import React from "react";
import { SingleProduct } from "../../../components/mainComponents/SingleProductsDetails";
import { BottomBar, Footer, Navbar } from "../../../components/sharedComponents";

const SingleProductPage = () => {
  return (
    <>
      <Head>
        <title>Store | Single Product </title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar />
      <SingleProduct />
      <BottomBar />
      <Footer />
    </>
  );
};

export default SingleProductPage;
