import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

const Error = () => {
  return (
    <>
      <Head>
        <title>Page Not Found</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ textAlign: "center", marginTop: "20vh" }}>
        <div>
          <Image src="/errorImg.png" width="200" height="250" alt="" priority />
        </div>
        <div className="">
          <p className="text-4xl font-bold text-primary">
            Oops! It looks like <br />
            you&apos;re lost
          </p>
          <p className="my-5 text-lg text-my-gray-200">
            .The page you&apos;re looking for isn&apos;t available. Try to search again or use the go to
          </p>
          <Link href="/">
            <a>
              <button className="button ">HOME PAGE</button>
            </a>
          </Link>
        </div>
      </div>
    </>
  );
};

export default Error;
